baseURL = "/"
languageCode = "fr"
title = "Promobras"
copyright = "Promobras"
disableKinds = ["RSS"]
enableRobotsTXT = true
disableAliases = true

RemovePathAccents = true
permalinks = "/:sections/:slug/"
sectionPagesMenu = "main"

[params]
tagline = "Agence de Voyage - Le Brésil Autrement - Agence de voyage à Lausanne spécialisée pour le Brésil - Lausanne"
slogan = "Le Brésil Autrement"
cloudinary = "dggfnr6w1"

# add redirects/headers
[outputs]
home = ["HTML", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
