backend:
  name: github
  repo: Promobras/website-hugo
  branch: html5up-twenty
  
media_folder: "src/images"
public_folder: "/images"
collections:
  
  - name: "destinations"
    label: "Destinations"
    folder: "content/destinations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link Title", name: "linktitle", widget: "string" }
      - { label: "Tag Line", name: "tagline", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "circuits"
    label: "Circuits"
    folder: "content/circuits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link Title", name: "linktitle", widget: "string" }
      - { label: "Tag Line", name: "tagline", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
